name: pytest

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - run: pip3 install pytest
      - run: python3 -m pytest
